### ISSUE TITLE
(Postgrex.QueryError) type `fieldname` can not be handled by the types module ParadexTest.PostgrexTypes

### ISSUE THREAD

**Issue by bgoosmanviz** [Moosieus/paradex#4]
This is probably my fault, but wondering if you can help. Banging my head against the wall on this one :).

```
paradex_test % mix test test/paradex_test/search_blog_posts_test.exs
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1730236566.328304 16066871 cpu_client.cc:474] TfrtCpuClient created.
Running ExUnit with seed: 944278, max_cases: 20

[%{id: 2, title: "The curious case of Goose 😗", score: 0.5897495150566101}]
.17:16:07.007 [error] Postgrex.Protocol (#PID<0.306.0>) disconnected: ** (Postgrex.QueryError) type `fieldname` can not be handled by the types module ParadexTest.PostgrexTypes


  1) test fuzzy term query (ParadexTest.SearchBlogPostsTest)
     test/paradex_test/search_blog_posts_test.exs:24
     ** (Postgrex.QueryError) type `fieldname` can not be handled by the types module ParadexTest.PostgrexTypes
     code: Repo.all(query) |> IO.inspect()
     stacktrace:
       (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
       (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
       (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
       test/paradex_test/search_blog_posts_test.exs:32: (test)
```

Test file

```
defmodule ParadexTest.SearchBlogPostsTest do
  use ParadexTest.DataCase

  import Ecto.Query
  import Paradex

  alias ParadexTest.Blog.Post
  alias ParadexTest.Repo

  test "term query" do
    search = ~s'goose'
    query =
      from(
        c in Post,
        select: %{id: c.id, score: score(c.id), title: c.title},
        # where: c.title ~> "goose"
        # where: c.title ~> ~s'goose'
        where: c.title ~> ^search
      )

    Repo.all(query) |> IO.inspect()
  end

  test "fuzzy term query" do
    column = "title"
    search = "goose"
    query = from(
        c in Post,
        select: %{id: c.id, score: score(c.id), title: c.title},
        where: c.title ~> fuzzy_term(^column, ^search, 2, true, false)
      )
    Repo.all(query) |> IO.inspect()
  end
end
```

**Comment by bgoosmanviz** [comment]
LOL, one second after posting, I try this and it works. What's the deal with ^column and ^search?

```
  test "fuzzy term query" do
    column = "title"
    search = "goose"

    query =
      from(
        c in Post,
        select: %{id: c.id, score: score(c.id), title: c.title},
        where: c.title ~> fuzzy_term("title", "goose", 2, true, false)
      )

    Repo.all(query) |> IO.inspect()
  end
```

**Comment by Moosieus** [comment]
`paradedb.fuzzy_term` is a [query object](https://docs.paradedb.com/documentation/advanced/overview), so the `key_field` on the left hand side. Assuming you set it to `id`:
```elixir
column = "title"
search = "goose"
    
from(
  p in Post,
  select: %{id: p.id, score: score(p.id), title: p.title},
  where: p.id ~> fuzzy_term(^column, ^search, 2, true, false)
)
```

Can you share the SQL your previous Ecto query produced? It might make sense to file an issue with the ParadeDB team, asking for a more explicit error message here.

**Comment by Moosieus** [comment]
Scratch that, I'm able to reproduce the error even with the above. I'll have to investigate further.

**Comment by Moosieus** [comment]
I spoke with Eric Ridge on the ParadeDB team. While parameterized column references are technically possible here, it's not really something Postgres nominally supports. For example, you couldn't do `WHERE $1 = $2`, where `$1` is a column reference.

That considered, I would stick to passing the column name as a literal:
```elixir
fuzzy_term("title", ^search, 2, true, false)
```

We could look at including a Postgrex Extension in this package to support the `paradedb.filedname` type, which would perhaps enable dynamic field addressing.

**Comment by eeeebbbbrrrr** [comment]
> fuzzy_term("title", ^search, 2, true, false)

I think you mean:

```sql
fuzzy_term('title', ^search, 2, true, false)
```

Note the single quotes around `title`, not double.

**Comment by bgoosmanviz** [comment]
I see. Thanks for pointing out that ^ syntax is for parameterization. I can understand that coming from Cypher, where it's required to hardcode column (property) names into queries, for query planning purposes. In the example, I honestly thought I was just inserting the column name as a variable, and not utilizing parameterization.

@eeeebbbbrrrr What's the difference between `'title'` and `"title"` in this example?

**Comment by bgoosmanviz** [comment]
Off topic, but can someone explain to me the intuition behind applying fuzzy_term to the key column?

**Comment by Moosieus** [comment]
@eeeebbbbrrrr That's Elixir code, specifically, Ecto's query DSL :D
```elixir
search = "goose"
    
from(
  p in Post,
  select: %{id: p.id, score: score(p.id), title: p.title},
  where: p.id ~> fuzzy_term("title", ^search, 2, true, false)
)
```

Elixir uses `""` for strings which Ecto translates to `''` for Postgres.

**Comment by Moosieus** [comment]
@bgoosmanviz I have a solution on the [field_names](https://github.com/Moosieus/paradex) branch that should handle parameterized field names.

You can try it out with this in your mix deps:
```elixir
{:paradex, git: "https://github.com/Moosieus/paradex", branch: "field_names"}
```

If it works for you, I'll publish it to Hex as `v0.3.0` promptly.

If you don't want to test it, I'll sleep on it for a bit and publish it later :stuck_out_tongue:

**Comment by bgoosmanviz** [comment]
Thanks @Moosieus!
